name: Docker image push

on:
  push:
    branches: master
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    -
     name: Checkout
     uses: actions/checkout@v2
    -
     name: Login to GitHub CR
     uses: docker/login-action@v1
     with:
       registry: ghcr.io
       username: ${{ github.actor }}
       password: ${{ secrets.GCR_PASSWORD }}
    -
     name: build and push the last docker image
     run: docker build -t ghrc.io/mariasanzs/makeupiv:latest . && docker push ghrc.io/mariasanzs/makeupiv:latest
